TEMPLATE	= app
LANGUAGE	= C++

CONFIG	+= qt warn_on release

HEADERS	+= client.h

SOURCES	+= main.cpp \
	client.cpp

FORMS	= moker.ui

######################################################################
# Automatically generated by qmake (1.07a) Fri Apr 14 15:49:29 2006
######################################################################


# Input
